version: '3.3'
services:
  app1:
    build: .
    environment:
      - app_name=app1
    ports:
      - 3001:3000
  app2:
    build: .
    environment:
      - app_name=app2
    ports:
      - 3002:3000
  app3:
    build: .
    environment:
      - app_name=app3
    ports:
      - 3003:3000